waypoint:
  use_yaml: true
  points :   
       - ["START",   471419.869724,                4167740.629269]
       - ["WP1",     471410.157533,                4167753.973662]
       - ["WP2",    471384.732122,                4167735.102006]
       - ["WP3",    471402.735208,                4167707.860495]
       - ["WP4",    471409.210002,                4167712.124383]
       - ["WP5",    471399.339889,                4167724.205401]